namespace CilDotNet
{
    public static class OpCodeTable
    {
        private static readonly Dictionary<OpCodeCategories, OpCode> opCodes = new();

        public static readonly OpCode Nop;
        public static readonly OpCode Break;
        public static readonly OpCode Ldarg0;
        public static readonly OpCode Ldarg1;
        public static readonly OpCode Ldarg2;
        public static readonly OpCode Ldarg3;
        public static readonly OpCode Ldloc0;
        public static readonly OpCode Ldloc1;
        public static readonly OpCode Ldloc2;
        public static readonly OpCode Ldloc3;
        public static readonly OpCode Stloc0;
        public static readonly OpCode Stloc1;
        public static readonly OpCode Stloc2;
        public static readonly OpCode Stloc3;
        public static readonly OpCode LdargS;
        public static readonly OpCode LdargaS;
        public static readonly OpCode StargS;
        public static readonly OpCode LdlocS;
        public static readonly OpCode LdlocaS;
        public static readonly OpCode StlocS;
        public static readonly OpCode Ldnull;
        public static readonly OpCode LdcI4M1;
        public static readonly OpCode LdcI4_0;
        public static readonly OpCode LdcI4_1;
        public static readonly OpCode LdcI4_2;
        public static readonly OpCode LdcI4_3;
        public static readonly OpCode LdcI4_4;
        public static readonly OpCode LdcI4_5;
        public static readonly OpCode LdcI4_6;
        public static readonly OpCode LdcI4_7;
        public static readonly OpCode LdcI4_8;
        public static readonly OpCode LdcI4S;
        public static readonly OpCode LdcI4;
        public static readonly OpCode LdcI8;
        public static readonly OpCode LdcR4;
        public static readonly OpCode LdcR8;
        public static readonly OpCode Dup;
        public static readonly OpCode Pop;
        public static readonly OpCode Jmp;
        public static readonly OpCode Call;
        public static readonly OpCode Calli;
        public static readonly OpCode Ret;
        public static readonly OpCode BrS;
        public static readonly OpCode BrfalseS;
        public static readonly OpCode BrtrueS;
        public static readonly OpCode BeqS;
        public static readonly OpCode BgeS;
        public static readonly OpCode BgtS;
        public static readonly OpCode BleS;
        public static readonly OpCode BltS;
        public static readonly OpCode BneUnS;
        public static readonly OpCode BgeUnS;
        public static readonly OpCode BgtUnS;
        public static readonly OpCode BleUnS;
        public static readonly OpCode BltUnS;
        public static readonly OpCode Br;
        public static readonly OpCode Brfalse;
        public static readonly OpCode Brtrue;
        public static readonly OpCode Beq;
        public static readonly OpCode Bge;
        public static readonly OpCode Bgt;
        public static readonly OpCode Ble;
        public static readonly OpCode Blt;
        public static readonly OpCode BneUn;
        public static readonly OpCode BgeUn;
        public static readonly OpCode BgtUn;
        public static readonly OpCode BleUn;
        public static readonly OpCode BltUn;
        public static readonly OpCode Switch;
        public static readonly OpCode LdindI1;
        public static readonly OpCode LdindU1;
        public static readonly OpCode LdindI2;
        public static readonly OpCode LdindU2;
        public static readonly OpCode LdindI4;
        public static readonly OpCode LdindU4;
        public static readonly OpCode LdindI8;
        public static readonly OpCode LdindI;
        public static readonly OpCode LdindR4;
        public static readonly OpCode LdindR8;
        public static readonly OpCode LdindRef;
        public static readonly OpCode StindRef;
        public static readonly OpCode StindI1;
        public static readonly OpCode StindI2;
        public static readonly OpCode StindI4;
        public static readonly OpCode StindI8;
        public static readonly OpCode StindR4;
        public static readonly OpCode StindR8;
        public static readonly OpCode StindI;
        public static readonly OpCode Add;
        public static readonly OpCode Sub;
        public static readonly OpCode Mul;
        public static readonly OpCode Div;
        public static readonly OpCode DivUn;
        public static readonly OpCode Rem;
        public static readonly OpCode RemUn;
        public static readonly OpCode And;
        public static readonly OpCode Or;
        public static readonly OpCode Xor;
        public static readonly OpCode Shl;
        public static readonly OpCode Shr;
        public static readonly OpCode ShrUn;
        public static readonly OpCode Neg;
        public static readonly OpCode Not;
        public static readonly OpCode ConvI1;
        public static readonly OpCode ConvI2;
        public static readonly OpCode ConvI4;
        public static readonly OpCode ConvI8;
        public static readonly OpCode ConvR4;
        public static readonly OpCode ConvR8;
        public static readonly OpCode ConvU4;
        public static readonly OpCode ConvU8;
        public static readonly OpCode Callvirt;
        public static readonly OpCode Cpobj;
        public static readonly OpCode Ldobj;
        public static readonly OpCode Ldstr;
        public static readonly OpCode Newobj;
        public static readonly OpCode Castclass;
        public static readonly OpCode Isinst;
        public static readonly OpCode ConvRUn;
        public static readonly OpCode Unbox;
        public static readonly OpCode Throw;
        public static readonly OpCode Ldfld;
        public static readonly OpCode Ldflda;
        public static readonly OpCode Stfld;
        public static readonly OpCode Ldsfld;
        public static readonly OpCode Ldsflda;
        public static readonly OpCode Stsfld;
        public static readonly OpCode Stobj;
        public static readonly OpCode ConvOvfI1Un;
        public static readonly OpCode ConvOvfI2Un;
        public static readonly OpCode ConvOvfI4Un;
        public static readonly OpCode ConvOvfI8Un;
        public static readonly OpCode ConvOvfU1Un;
        public static readonly OpCode ConvOvfU2Un;
        public static readonly OpCode ConvOvfU4Un;
        public static readonly OpCode ConvOvfU8Un;
        public static readonly OpCode ConvOvfIUn;
        public static readonly OpCode ConvOvfUUn;
        public static readonly OpCode Box;
        public static readonly OpCode Newarr;
        public static readonly OpCode Ldlen;
        public static readonly OpCode Ldelema;
        public static readonly OpCode LdelemI1;
        public static readonly OpCode LdelemU1;
        public static readonly OpCode LdelemI2;
        public static readonly OpCode LdelemU2;
        public static readonly OpCode LdelemI4;
        public static readonly OpCode LdelemU4;
        public static readonly OpCode LdelemI8;
        public static readonly OpCode LdelemI;
        public static readonly OpCode LdelemR4;
        public static readonly OpCode LdelemR8;
        public static readonly OpCode LdelemRef;
        public static readonly OpCode StelemI;
        public static readonly OpCode StelemI1;
        public static readonly OpCode StelemI2;
        public static readonly OpCode StelemI4;
        public static readonly OpCode StelemI8;
        public static readonly OpCode StelemR4;
        public static readonly OpCode StelemR8;
        public static readonly OpCode StelemRef;
        public static readonly OpCode LdelemAny;
        public static readonly OpCode StelemAny;
        public static readonly OpCode UnboxAny;
        public static readonly OpCode ConvOvfI1;
        public static readonly OpCode ConvOvfU1;
        public static readonly OpCode ConvOvfI2;
        public static readonly OpCode ConvOvfU2;
        public static readonly OpCode ConvOvfI4;
        public static readonly OpCode ConvOvfU4;
        public static readonly OpCode ConvOvfI8;
        public static readonly OpCode ConvOvfU8;
        public static readonly OpCode Refanyval;
        public static readonly OpCode Ckfinite;
        public static readonly OpCode Mkrefany;
        public static readonly OpCode Ldtoken;
        public static readonly OpCode ConvU2;
        public static readonly OpCode ConvU1;
        public static readonly OpCode ConvI;
        public static readonly OpCode ConvOvfI;
        public static readonly OpCode ConvOvfU;
        public static readonly OpCode AddOvf;
        public static readonly OpCode AddOvfUn;
        public static readonly OpCode MulOvf;
        public static readonly OpCode MulOvfUn;
        public static readonly OpCode SubOvf;
        public static readonly OpCode SubOvfUn;
        public static readonly OpCode Endfinally;
        public static readonly OpCode Leave;
        public static readonly OpCode LeaveS;
        public static readonly OpCode ConvU;
        public static readonly OpCode Arglist;
        public static readonly OpCode Ceq;
        public static readonly OpCode Cgt;
        public static readonly OpCode CgtUn;
        public static readonly OpCode Clt;
        public static readonly OpCode CltUn;
        public static readonly OpCode Ldftn;
        public static readonly OpCode Ldvirtftn;
        public static readonly OpCode Ldarg;
        public static readonly OpCode Ldarga;
        public static readonly OpCode Starg;
        public static readonly OpCode Ldloc;
        public static readonly OpCode Ldloca;
        public static readonly OpCode Stloc;
        public static readonly OpCode Localloc;
        public static readonly OpCode Endfilter;
        public static readonly OpCode Unaligned;
        public static readonly OpCode Volatile;
        public static readonly OpCode Tail;
        public static readonly OpCode Initobj;
        public static readonly OpCode Constrained;
        public static readonly OpCode Cpblk;
        public static readonly OpCode Initblk;
        public static readonly OpCode Rethrow;
        public static readonly OpCode Sizeof;
        public static readonly OpCode Refanytype;
        public static readonly OpCode Readonly;

        static OpCodeTable()
        {
            Nop = Register("nop", OpCodeCategories.Nop, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            Break = Register("break", OpCodeCategories.Break, OperandType.None, CilDotNet.Cil.FlowControl.Branch);
            Ldarg0 = Register("ldarg.0", OpCodeCategories.Ldarg0, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            Ldarg1 = Register("ldarg.1", OpCodeCategories.Ldarg1, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            Ldarg2 = Register("ldarg.2", OpCodeCategories.Ldarg2, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            Ldarg3 = Register("ldarg.3", OpCodeCategories.Ldarg3, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            Ldloc0 = Register("ldloc.0", OpCodeCategories.Ldloc0, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            Ldloc1 = Register("ldloc.1", OpCodeCategories.Ldloc1, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            Ldloc2 = Register("ldloc.2", OpCodeCategories.Ldloc2, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            Ldloc3 = Register("ldloc.3", OpCodeCategories.Ldloc3, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            Stloc0 = Register("stloc.0", OpCodeCategories.Stloc0, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            Stloc1 = Register("stloc.1", OpCodeCategories.Stloc1, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            Stloc2 = Register("stloc.2", OpCodeCategories.Stloc2, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            Stloc3 = Register("stloc.3", OpCodeCategories.Stloc3, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            LdargS = Register("ldarg.s", OpCodeCategories.LdargS, OperandType.ShortInlineParam, CilDotNet.Cil.FlowControl.Next);
            LdargaS = Register("ldarga.s", OpCodeCategories.LdargaS, OperandType.ShortInlineParam, CilDotNet.Cil.FlowControl.Next);
            StargS = Register("starg.s", OpCodeCategories.StargS, OperandType.ShortInlineParam, CilDotNet.Cil.FlowControl.Next);
            LdlocS = Register("ldloc.s", OpCodeCategories.LdlocS, OperandType.ShortInlineVar, CilDotNet.Cil.FlowControl.Next);
            LdlocaS = Register("ldloca.s", OpCodeCategories.LdlocaS, OperandType.ShortInlineVar, CilDotNet.Cil.FlowControl.Next);
            StlocS = Register("stloc.s", OpCodeCategories.StlocS, OperandType.ShortInlineVar, CilDotNet.Cil.FlowControl.Next);
            Ldnull = Register("ldnull", OpCodeCategories.Ldnull, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            LdcI4M1 = Register("ldc.i4.m1", OpCodeCategories.LdcI4M1, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            LdcI4_0 = Register("ldc.i4.0", OpCodeCategories.LdcI4_0, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            LdcI4_1 = Register("ldc.i4.1", OpCodeCategories.LdcI4_1, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            LdcI4_2 = Register("ldc.i4.2", OpCodeCategories.LdcI4_2, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            LdcI4_3 = Register("ldc.i4.3", OpCodeCategories.LdcI4_3, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            LdcI4_4 = Register("ldc.i4.4", OpCodeCategories.LdcI4_4, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            LdcI4_5 = Register("ldc.i4.5", OpCodeCategories.LdcI4_5, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            LdcI4_6 = Register("ldc.i4.6", OpCodeCategories.LdcI4_6, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            LdcI4_7 = Register("ldc.i4.7", OpCodeCategories.LdcI4_7, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            LdcI4_8 = Register("ldc.i4.8", OpCodeCategories.LdcI4_8, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            LdcI4S = Register("ldc.i4.s", OpCodeCategories.LdcI4S, OperandType.ShortInlineI, CilDotNet.Cil.FlowControl.Next);
            LdcI4 = Register("ldc.i4", OpCodeCategories.LdcI4, OperandType.InlineI, CilDotNet.Cil.FlowControl.Next);
            LdcI8 = Register("ldc.i8", OpCodeCategories.LdcI8, OperandType.InlineI8, CilDotNet.Cil.FlowControl.Next);
            LdcR4 = Register("ldc.r4", OpCodeCategories.LdcR4, OperandType.ShortInlineR, CilDotNet.Cil.FlowControl.Next);
            LdcR8 = Register("ldc.r8", OpCodeCategories.LdcR8, OperandType.InlineR, CilDotNet.Cil.FlowControl.Next);
            Dup = Register("dup", OpCodeCategories.Dup, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            Pop = Register("pop", OpCodeCategories.Pop, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            Jmp = Register("jmp", OpCodeCategories.Jmp, OperandType.InlineMethod, CilDotNet.Cil.FlowControl.Call);
            Call = Register("call", OpCodeCategories.Call, OperandType.InlineMethod, CilDotNet.Cil.FlowControl.Call);
            Calli = Register("calli", OpCodeCategories.Calli, OperandType.InlineSig, CilDotNet.Cil.FlowControl.Call);
            Ret = Register("ret", OpCodeCategories.Ret, OperandType.None, CilDotNet.Cil.FlowControl.Return);
            BrS = Register("br.s", OpCodeCategories.BrS, OperandType.ShortInlineBrTarget, CilDotNet.Cil.FlowControl.Branch);
            BrfalseS = Register("brfalse.s", OpCodeCategories.BrfalseS, OperandType.ShortInlineBrTarget, CilDotNet.Cil.FlowControl.CondBranch);
            BrtrueS = Register("brtrue.s", OpCodeCategories.BrtrueS, OperandType.ShortInlineBrTarget, CilDotNet.Cil.FlowControl.CondBranch);
            BeqS = Register("beq.s", OpCodeCategories.BeqS, OperandType.ShortInlineBrTarget, CilDotNet.Cil.FlowControl.CondBranch);
            BgeS = Register("bge.s", OpCodeCategories.BgeS, OperandType.ShortInlineBrTarget, CilDotNet.Cil.FlowControl.CondBranch);
            BgtS = Register("bgt.s", OpCodeCategories.BgtS, OperandType.ShortInlineBrTarget, CilDotNet.Cil.FlowControl.CondBranch);
            BleS = Register("ble.s", OpCodeCategories.BleS, OperandType.ShortInlineBrTarget, CilDotNet.Cil.FlowControl.CondBranch);
            BltS = Register("blt.s", OpCodeCategories.BltS, OperandType.ShortInlineBrTarget, CilDotNet.Cil.FlowControl.CondBranch);
            BneUnS = Register("bne.un.s", OpCodeCategories.BneUnS, OperandType.ShortInlineBrTarget, CilDotNet.Cil.FlowControl.CondBranch);
            BgeUnS = Register("bge.un.s", OpCodeCategories.BgeUnS, OperandType.ShortInlineBrTarget, CilDotNet.Cil.FlowControl.CondBranch);
            BgtUnS = Register("bgt.un.s", OpCodeCategories.BgtUnS, OperandType.ShortInlineBrTarget, CilDotNet.Cil.FlowControl.CondBranch);
            BleUnS = Register("ble.un.s", OpCodeCategories.BleUnS, OperandType.ShortInlineBrTarget, CilDotNet.Cil.FlowControl.CondBranch);
            BltUnS = Register("blt.un.s", OpCodeCategories.BltUnS, OperandType.ShortInlineBrTarget, CilDotNet.Cil.FlowControl.CondBranch);
            Br = Register("br", OpCodeCategories.Br, OperandType.InlineBrTarget, CilDotNet.Cil.FlowControl.Branch);
            Brfalse = Register("brfalse", OpCodeCategories.Brfalse, OperandType.InlineBrTarget, CilDotNet.Cil.FlowControl.CondBranch);
            Brtrue = Register("brtrue", OpCodeCategories.Brtrue, OperandType.InlineBrTarget, CilDotNet.Cil.FlowControl.CondBranch);
            Beq = Register("beq", OpCodeCategories.Beq, OperandType.InlineBrTarget, CilDotNet.Cil.FlowControl.CondBranch);
            Bge = Register("bge", OpCodeCategories.Bge, OperandType.InlineBrTarget, CilDotNet.Cil.FlowControl.CondBranch);
            Bgt = Register("bgt", OpCodeCategories.Bgt, OperandType.InlineBrTarget, CilDotNet.Cil.FlowControl.CondBranch);
            Ble = Register("ble", OpCodeCategories.Ble, OperandType.InlineBrTarget, CilDotNet.Cil.FlowControl.CondBranch);
            Blt = Register("blt", OpCodeCategories.Blt, OperandType.InlineBrTarget, CilDotNet.Cil.FlowControl.CondBranch);
            BneUn = Register("bne.un", OpCodeCategories.BneUn, OperandType.InlineBrTarget, CilDotNet.Cil.FlowControl.CondBranch);
            BgeUn = Register("bge.un", OpCodeCategories.BgeUn, OperandType.InlineBrTarget, CilDotNet.Cil.FlowControl.CondBranch);
            BgtUn = Register("bgt.un", OpCodeCategories.BgtUn, OperandType.InlineBrTarget, CilDotNet.Cil.FlowControl.CondBranch);
            BleUn = Register("ble.un", OpCodeCategories.BleUn, OperandType.InlineBrTarget, CilDotNet.Cil.FlowControl.CondBranch);
            BltUn = Register("blt.un", OpCodeCategories.BltUn, OperandType.InlineBrTarget, CilDotNet.Cil.FlowControl.CondBranch);
            Switch = Register("switch", OpCodeCategories.Switch, OperandType.InlineSwitch, CilDotNet.Cil.FlowControl.CondBranch);
            LdindI1 = Register("ldind.i1", OpCodeCategories.LdindI1, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            LdindU1 = Register("ldind.u1", OpCodeCategories.LdindU1, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            LdindI2 = Register("ldind.i2", OpCodeCategories.LdindI2, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            LdindU2 = Register("ldind.u2", OpCodeCategories.LdindU2, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            LdindI4 = Register("ldind.i4", OpCodeCategories.LdindI4, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            LdindU4 = Register("ldind.u4", OpCodeCategories.LdindU4, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            LdindI8 = Register("ldind.i8", OpCodeCategories.LdindI8, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            LdindI = Register("ldind.i", OpCodeCategories.LdindI, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            LdindR4 = Register("ldind.r4", OpCodeCategories.LdindR4, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            LdindR8 = Register("ldind.r8", OpCodeCategories.LdindR8, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            LdindRef = Register("ldind.ref", OpCodeCategories.LdindRef, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            StindRef = Register("stind.ref", OpCodeCategories.StindRef, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            StindI1 = Register("stind.i1", OpCodeCategories.StindI1, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            StindI2 = Register("stind.i2", OpCodeCategories.StindI2, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            StindI4 = Register("stind.i4", OpCodeCategories.StindI4, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            StindI8 = Register("stind.i8", OpCodeCategories.StindI8, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            StindR4 = Register("stind.r4", OpCodeCategories.StindR4, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            StindR8 = Register("stind.r8", OpCodeCategories.StindR8, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            StindI = Register("stind.i", OpCodeCategories.StindI, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            Add = Register("add", OpCodeCategories.Add, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            Sub = Register("sub", OpCodeCategories.Sub, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            Mul = Register("mul", OpCodeCategories.Mul, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            Div = Register("div", OpCodeCategories.Div, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            DivUn = Register("div.un", OpCodeCategories.DivUn, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            Rem = Register("rem", OpCodeCategories.Rem, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            RemUn = Register("rem.un", OpCodeCategories.RemUn, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            And = Register("and", OpCodeCategories.And, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            Or = Register("or", OpCodeCategories.Or, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            Xor = Register("xor", OpCodeCategories.Xor, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            Shl = Register("shl", OpCodeCategories.Shl, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            Shr = Register("shr", OpCodeCategories.Shr, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            ShrUn = Register("shr.un", OpCodeCategories.ShrUn, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            Neg = Register("neg", OpCodeCategories.Neg, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            Not = Register("not", OpCodeCategories.Not, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            ConvI1 = Register("conv.i1", OpCodeCategories.ConvI1, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            ConvI2 = Register("conv.i2", OpCodeCategories.ConvI2, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            ConvI4 = Register("conv.i4", OpCodeCategories.ConvI4, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            ConvI8 = Register("conv.i8", OpCodeCategories.ConvI8, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            ConvR4 = Register("conv.r4", OpCodeCategories.ConvR4, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            ConvR8 = Register("conv.r8", OpCodeCategories.ConvR8, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            ConvU4 = Register("conv.u4", OpCodeCategories.ConvU4, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            ConvU8 = Register("conv.u8", OpCodeCategories.ConvU8, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            Callvirt = Register("callvirt", OpCodeCategories.Callvirt, OperandType.InlineMethod, CilDotNet.Cil.FlowControl.Call);
            Cpobj = Register("cpobj", OpCodeCategories.Cpobj, OperandType.InlineType, CilDotNet.Cil.FlowControl.Next);
            Ldobj = Register("ldobj", OpCodeCategories.Ldobj, OperandType.InlineType, CilDotNet.Cil.FlowControl.Next);
            Ldstr = Register("ldstr", OpCodeCategories.Ldstr, OperandType.InlineString, CilDotNet.Cil.FlowControl.Next);
            Newobj = Register("newobj", OpCodeCategories.Newobj, OperandType.InlineMethod, CilDotNet.Cil.FlowControl.Call);
            Castclass = Register("castclass", OpCodeCategories.Castclass, OperandType.InlineType, CilDotNet.Cil.FlowControl.Next);
            Isinst = Register("isinst", OpCodeCategories.Isinst, OperandType.InlineType, CilDotNet.Cil.FlowControl.Next);
            ConvRUn = Register("conv.r.un", OpCodeCategories.ConvRUn, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            Unbox = Register("unbox", OpCodeCategories.Unbox, OperandType.InlineType, CilDotNet.Cil.FlowControl.Next);
            Throw = Register("throw", OpCodeCategories.Throw, OperandType.None, CilDotNet.Cil.FlowControl.Throw);
            Ldfld = Register("ldfld", OpCodeCategories.Ldfld, OperandType.InlineField, CilDotNet.Cil.FlowControl.Next);
            Ldflda = Register("ldflda", OpCodeCategories.Ldflda, OperandType.InlineField, CilDotNet.Cil.FlowControl.Next);
            Stfld = Register("stfld", OpCodeCategories.Stfld, OperandType.InlineField, CilDotNet.Cil.FlowControl.Next);
            Ldsfld = Register("ldsfld", OpCodeCategories.Ldsfld, OperandType.InlineField, CilDotNet.Cil.FlowControl.Next);
            Ldsflda = Register("ldsflda", OpCodeCategories.Ldsflda, OperandType.InlineField, CilDotNet.Cil.FlowControl.Next);
            Stsfld = Register("stsfld", OpCodeCategories.Stsfld, OperandType.InlineField, CilDotNet.Cil.FlowControl.Next);
            Stobj = Register("stobj", OpCodeCategories.Stobj, OperandType.InlineType, CilDotNet.Cil.FlowControl.Next);
            ConvOvfI1Un = Register("conv.ovf.i1.un", OpCodeCategories.ConvOvfI1Un, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            ConvOvfI2Un = Register("conv.ovf.i2.un", OpCodeCategories.ConvOvfI2Un, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            ConvOvfI4Un = Register("conv.ovf.i4.un", OpCodeCategories.ConvOvfI4Un, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            ConvOvfI8Un = Register("conv.ovf.i8.un", OpCodeCategories.ConvOvfI8Un, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            ConvOvfU1Un = Register("conv.ovf.u1.un", OpCodeCategories.ConvOvfU1Un, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            ConvOvfU2Un = Register("conv.ovf.u2.un", OpCodeCategories.ConvOvfU2Un, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            ConvOvfU4Un = Register("conv.ovf.u4.un", OpCodeCategories.ConvOvfU4Un, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            ConvOvfU8Un = Register("conv.ovf.u8.un", OpCodeCategories.ConvOvfU8Un, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            ConvOvfIUn = Register("conv.ovf.i.un", OpCodeCategories.ConvOvfIUn, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            ConvOvfUUn = Register("conv.ovf.u.un", OpCodeCategories.ConvOvfUUn, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            Box = Register("box", OpCodeCategories.Box, OperandType.InlineType, CilDotNet.Cil.FlowControl.Next);
            Newarr = Register("newarr", OpCodeCategories.Newarr, OperandType.InlineType, CilDotNet.Cil.FlowControl.Next);
            Ldlen = Register("ldlen", OpCodeCategories.Ldlen, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            Ldelema = Register("ldelema", OpCodeCategories.Ldelema, OperandType.InlineType, CilDotNet.Cil.FlowControl.Next);
            LdelemI1 = Register("ldelem.i1", OpCodeCategories.LdelemI1, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            LdelemU1 = Register("ldelem.u1", OpCodeCategories.LdelemU1, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            LdelemI2 = Register("ldelem.i2", OpCodeCategories.LdelemI2, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            LdelemU2 = Register("ldelem.u2", OpCodeCategories.LdelemU2, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            LdelemI4 = Register("ldelem.i4", OpCodeCategories.LdelemI4, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            LdelemU4 = Register("ldelem.u4", OpCodeCategories.LdelemU4, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            LdelemI8 = Register("ldelem.i8", OpCodeCategories.LdelemI8, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            LdelemI = Register("ldelem.i", OpCodeCategories.LdelemI, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            LdelemR4 = Register("ldelem.r4", OpCodeCategories.LdelemR4, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            LdelemR8 = Register("ldelem.r8", OpCodeCategories.LdelemR8, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            LdelemRef = Register("ldelem.ref", OpCodeCategories.LdelemRef, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            StelemI = Register("stelem.i", OpCodeCategories.StelemI, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            StelemI1 = Register("stelem.i1", OpCodeCategories.StelemI1, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            StelemI2 = Register("stelem.i2", OpCodeCategories.StelemI2, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            StelemI4 = Register("stelem.i4", OpCodeCategories.StelemI4, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            StelemI8 = Register("stelem.i8", OpCodeCategories.StelemI8, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            StelemR4 = Register("stelem.r4", OpCodeCategories.StelemR4, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            StelemR8 = Register("stelem.r8", OpCodeCategories.StelemR8, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            StelemRef = Register("stelem.ref", OpCodeCategories.StelemRef, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            LdelemAny = Register("ldelem.any", OpCodeCategories.LdelemAny, OperandType.InlineType, CilDotNet.Cil.FlowControl.Next);
            StelemAny = Register("stelem.any", OpCodeCategories.StelemAny, OperandType.InlineType, CilDotNet.Cil.FlowControl.Next);
            UnboxAny = Register("unbox.any", OpCodeCategories.UnboxAny, OperandType.InlineType, CilDotNet.Cil.FlowControl.Next);
            ConvOvfI1 = Register("conv.ovf.i1", OpCodeCategories.ConvOvfI1, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            ConvOvfU1 = Register("conv.ovf.u1", OpCodeCategories.ConvOvfU1, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            ConvOvfI2 = Register("conv.ovf.i2", OpCodeCategories.ConvOvfI2, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            ConvOvfU2 = Register("conv.ovf.u2", OpCodeCategories.ConvOvfU2, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            ConvOvfI4 = Register("conv.ovf.i4", OpCodeCategories.ConvOvfI4, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            ConvOvfU4 = Register("conv.ovf.u4", OpCodeCategories.ConvOvfU4, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            ConvOvfI8 = Register("conv.ovf.i8", OpCodeCategories.ConvOvfI8, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            ConvOvfU8 = Register("conv.ovf.u8", OpCodeCategories.ConvOvfU8, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            Refanyval = Register("refanyval", OpCodeCategories.Refanyval, OperandType.InlineType, CilDotNet.Cil.FlowControl.Next);
            Ckfinite = Register("ckfinite", OpCodeCategories.Ckfinite, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            Mkrefany = Register("mkrefany", OpCodeCategories.Mkrefany, OperandType.InlineType, CilDotNet.Cil.FlowControl.Next);
            Ldtoken = Register("ldtoken", OpCodeCategories.Ldtoken, OperandType.InlineTok, CilDotNet.Cil.FlowControl.Next);
            ConvU2 = Register("conv.u2", OpCodeCategories.ConvU2, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            ConvU1 = Register("conv.u1", OpCodeCategories.ConvU1, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            ConvI = Register("conv.i", OpCodeCategories.ConvI, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            ConvOvfI = Register("conv.ovf.i", OpCodeCategories.ConvOvfI, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            ConvOvfU = Register("conv.ovf.u", OpCodeCategories.ConvOvfU, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            AddOvf = Register("add.ovf", OpCodeCategories.AddOvf, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            AddOvfUn = Register("add.ovf.un", OpCodeCategories.AddOvfUn, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            MulOvf = Register("mul.ovf", OpCodeCategories.MulOvf, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            MulOvfUn = Register("mul.ovf.un", OpCodeCategories.MulOvfUn, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            SubOvf = Register("sub.ovf", OpCodeCategories.SubOvf, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            SubOvfUn = Register("sub.ovf.un", OpCodeCategories.SubOvfUn, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            Endfinally = Register("endfinally", OpCodeCategories.Endfinally, OperandType.None, CilDotNet.Cil.FlowControl.Return);
            Leave = Register("leave", OpCodeCategories.Leave, OperandType.InlineBrTarget, CilDotNet.Cil.FlowControl.Branch);
            LeaveS = Register("leave.s", OpCodeCategories.LeaveS, OperandType.ShortInlineBrTarget, CilDotNet.Cil.FlowControl.Branch);
            ConvU = Register("conv.u", OpCodeCategories.ConvU, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            Arglist = Register("arglist", OpCodeCategories.Arglist, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            Ceq = Register("ceq", OpCodeCategories.Ceq, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            Cgt = Register("cgt", OpCodeCategories.Cgt, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            CgtUn = Register("cgt.un", OpCodeCategories.CgtUn, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            Clt = Register("clt", OpCodeCategories.Clt, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            CltUn = Register("clt.un", OpCodeCategories.CltUn, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            Ldftn = Register("ldftn", OpCodeCategories.Ldftn, OperandType.InlineMethod, CilDotNet.Cil.FlowControl.Next);
            Ldvirtftn = Register("ldvirtftn", OpCodeCategories.Ldvirtftn, OperandType.InlineMethod, CilDotNet.Cil.FlowControl.Next);
            Ldarg = Register("ldarg", OpCodeCategories.Ldarg, OperandType.InlineParam, CilDotNet.Cil.FlowControl.Next);
            Ldarga = Register("ldarga", OpCodeCategories.Ldarga, OperandType.InlineParam, CilDotNet.Cil.FlowControl.Next);
            Starg = Register("starg", OpCodeCategories.Starg, OperandType.InlineParam, CilDotNet.Cil.FlowControl.Next);
            Ldloc = Register("ldloc", OpCodeCategories.Ldloc, OperandType.InlineVar, CilDotNet.Cil.FlowControl.Next);
            Ldloca = Register("ldloca", OpCodeCategories.Ldloca, OperandType.InlineVar, CilDotNet.Cil.FlowControl.Next);
            Stloc = Register("stloc", OpCodeCategories.Stloc, OperandType.InlineVar, CilDotNet.Cil.FlowControl.Next);
            Localloc = Register("localloc", OpCodeCategories.Localloc, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            Endfilter = Register("endfilter", OpCodeCategories.Endfilter, OperandType.None, CilDotNet.Cil.FlowControl.Return);
            Unaligned = Register("unaligned.", OpCodeCategories.Unaligned, OperandType.ShortInlineI, CilDotNet.Cil.FlowControl.Meta);
            Volatile = Register("volatile.", OpCodeCategories.Volatile, OperandType.None, CilDotNet.Cil.FlowControl.Meta);
            Tail = Register("tail.", OpCodeCategories.Tail, OperandType.None, CilDotNet.Cil.FlowControl.Meta);
            Initobj = Register("initobj", OpCodeCategories.Initobj, OperandType.InlineType, CilDotNet.Cil.FlowControl.Next);
            Constrained = Register("constrained.", OpCodeCategories.Constrained, OperandType.InlineType, CilDotNet.Cil.FlowControl.Meta);
            Cpblk = Register("cpblk", OpCodeCategories.Cpblk, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            Initblk = Register("initblk", OpCodeCategories.Initblk, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            Rethrow = Register("rethrow", OpCodeCategories.Rethrow, OperandType.None, CilDotNet.Cil.FlowControl.Throw);
            Sizeof = Register("sizeof", OpCodeCategories.Sizeof, OperandType.InlineType, CilDotNet.Cil.FlowControl.Next);
            Refanytype = Register("refanytype", OpCodeCategories.Refanytype, OperandType.None, CilDotNet.Cil.FlowControl.Next);
            Readonly = Register("readonly.", OpCodeCategories.Readonly, OperandType.None, CilDotNet.Cil.FlowControl.Meta);
        }

        private static OpCode Register(string name, OpCodeCategories code, OperandType operandType, CilDotNet.Cil.FlowControl flowControl)
        {
            var opCode = new OpCode(name, code, operandType, flowControl);
            opCodes[code] = opCode;
            return opCode;
        }

        public static OpCode? Get(OpCodeCategories code)
        {
            return opCodes.TryGetValue(code, out var opCode) ? opCode : null;
        }

        public static OpCode? Get(byte b1, byte b2)
        {
            if (b1 == 0xFE)
            {
                var code = (OpCodeCategories)(0xFE00 | b2);
                return Get(code);
            }

            var singleCode = (OpCodeCategories)b1;
            return Get(singleCode);
        }

        public static IReadOnlyDictionary<OpCodeCategories, OpCode> All => opCodes;
    }
}